# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Post.destroy_all
User.destroy_all

user1 = User.create(username: "Guest", password: 'password', email: 'something@gmail.com')
user2 = User.create(username: "Tony", password: 'password', email: 'tony@gmail.com')
user3 = User.create(username: "Gamer24", password: 'password', email: 'jack@gmail.com')
user4 = User.create(username: "Amanda", password: 'password', email: 'eeyore@gmail.com')
user5 = User.create(username: "CandyTea", password: 'password', email: 'candy@gmail.com')
user6 = User.create(username: "Mithra", password: 'password', email: 'mithra@gmail.com')
user7 = User.create(username: "Anon", password: 'password', email: 'reaper0@gmail.com')
user8 = User.create(username: "Lunafreya", password: 'password', email: 'luna@gmail.com')
user9 = User.create(username: "Noctis", password: 'password', email: 'lucis@gmail.com')

user2.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'avatars', 'cookiemonster.png')), filename: 'cookiemonster.png', content_type: 'image/png')
user3.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'avatars', 'gamer24.png')), filename: 'gamer24.png', content_type: 'image/png')
user4.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'avatars', 'kitty.png')), filename: 'kitty.png', content_type: 'image/png')
user5.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'avatars', 'candycorn.jpg')), filename: 'candycorn.jpg', content_type: 'image/jpg')
user6.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'avatars', 'icon7.jpg')), filename: 'icon7.jpg', content_type: 'image/jpg')
user7.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'avatars', 'icon2.jpg')), filename: 'icon2.jpg', content_type: 'image/jpg')
user8.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'avatars', 'icon3.jpg')), filename: 'icon3.jpg', content_type: 'image/jpg')


# Post.create(author_id: user2.id, title:"http://en.akinator.com/", body:"Spent so many hours on this site, back in the day.", post_type: "link")
# Post.create(author_id: user4.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/photos/waffles.jpg", body:"Fried chicken & avocado on waffle toast w/ peppery aleppo honey", post_type:"photo")
# Post.create(author_id: user1.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/photos/texas.jpg", body:"Westcave Preserve, Texas. The 30 mile drive was absolutely worth it! My only regret was having to leave...", post_type:"photo")
# Post.create(author_id: user8.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/opal.jpg", body:"It's almost a shame that I've only just learned of Fire Opals. They're absolutely gorgeous.", post_type:"photo")
# Post.create(author_id: user4.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/14+Sun+Skip.mp3", body:"Can't wait for her concert in August!", post_type:"audio")
# Post.create(author_id: user8.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/leaves.gif", body:"Autumn in Japan", post_type:"photo")
# Post.create(author_id: user3.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/photos/pizza.jpg", body:"All this food that I'm craving!!!", post_type:"photo")
# Post.create(author_id: user4.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/photos/waterfall+resize.gif", post_type:"photo")
# Post.create(author_id: user5.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/cake.jpg", body:"First attempt at a mirror glaze! How'd I do?", post_type:"photo")
# Post.create(author_id: user6.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/posts/silverback.jpg", body:"We aren't so different, you and I", post_type:"photo")
# Post.create(author_id: user7.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/Macarons.jpg", body:"Picked these up over the weekend. Sooooo good.", post_type:"photo")
# Post.create(author_id: user2.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/photos/bridge+duel.gif", body:"At a crossing, you encounter a certain knight.", post_type:"photo")
# Post.create(author_id: user3.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/Footsteps+in+the+Snow+-+FFXIV.mp3", body:"Best track from the FFXIV OST, at least pre-Heavensward! Counting down the days until the expac lands!", post_type:"audio")
# Post.create(author_id: user6.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/photos/city.gif", post_type:"photo")
# Post.create(author_id: user7.id, source:"https://s3-us-west-1.amazonaws.com/mixr-dev/videos/night+gif.mp4", body:"Something about this is so appealing to me right now.", post_type:"video")
#
#
#
# Follow.create(followee_id: user8.id, follower_id: user1.id)
# Follow.create(followee_id: user4.id, follower_id: user1.id)
# Follow.create(followee_id: user5.id, follower_id: user1.id)
# Follow.create(followee_id: user6.id, follower_id: user1.id)
#
# Like.create(user_id: 5, post_id: 1)
# Like.create(user_id: 5, post_id: 2)
# Like.create(user_id: 5, post_id: 3)
# Like.create(user_id: 5, post_id: 4)
# Like.create(user_id: 5, post_id: 5)
# Like.create(user_id: 7, post_id: 1)
# Like.create(user_id: 7, post_id: 2)
# Like.create(user_id: 7, post_id: 3)
# Like.create(user_id: 7, post_id: 4)
# Like.create(user_id: 7, post_id: 5)
# Like.create(user_id: 6, post_id: 1)
# Like.create(user_id: 6, post_id: 2)
# Like.create(user_id: 6, post_id: 3)
# Like.create(user_id: 6, post_id: 4)
# Like.create(user_id: 6, post_id: 5)
# Like.create(user_id: 5, post_id: 8)
# Like.create(user_id: 6, post_id: 7)
# Like.create(user_id: 6, post_id: 8)
# Like.create(user_id: 6, post_id: 9)
# Like.create(user_id: 6, post_id: 10)
# Like.create(user_id: 6, post_id: 6)
# Like.create(user_id: 6, post_id: 8)
#
# Like.create(user_id: 2, post_id: 11)
# Like.create(user_id: 2, post_id: 9)
# Like.create(user_id: 2, post_id: 8)
# Like.create(user_id: 2, post_id: 7)
# Like.create(user_id: 2, post_id: 12)
# Like.create(user_id: 2, post_id: 13)
# Like.create(user_id: 3, post_id: 11)
# Like.create(user_id: 3, post_id: 9)
# Like.create(user_id: 3, post_id: 8)
# Like.create(user_id: 3, post_id: 7)
# Like.create(user_id: 3, post_id: 12)
# Like.create(user_id: 3, post_id: 13)
#
# Like.create(user_id: 3, post_id: 14)
# Like.create(user_id: 2, post_id: 14)
# Like.create(user_id: 1, post_id: 14)
# Like.create(user_id: 6, post_id: 14)
# Like.create(user_id: 7, post_id: 14)
# Like.create(user_id: 4, post_id: 14)
# Like.create(user_id: 2, post_id: 13)
# Like.create(user_id: 1, post_id: 13)
# Like.create(user_id: 6, post_id: 13)
# Like.create(user_id: 7, post_id: 13)
# Like.create(user_id: 4, post_id: 13)
